name: Start Drawing Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          python3 --version

      - name: Install Python dependencies globally
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      # Step 4: Generate Python scripts
      - name: Generate Python scripts from Secrets
        env:
          ARTISTIC_PAINTING_PROCESSOR: "${{ secrets.ARTISTIC_PAINTING_PROCESSOR }}"
          ADD_FADING_EDGES: "${{ secrets.ADD_FADING_EDGES }}"
        run: python3 generate_scripts.py

      # Step 5: Run generated Python scripts
      - name: Run artistic painting processor
        run: python3 artistic_painting_processor.py

      - name: Run fading edges processor
        run: python3 add_fading_edges.py



