name: Start Drawing Workflow

on:
  workflow_dispatch:
  push:

jobs:
  start-drawing-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          python3 --version

      - name: Install Python dependencies globally
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Install dependencies
        run: |
          pip install dropbox requests

      - name: Create required folders
        run: |
          mkdir -p original_photos
          mkdir -p converted_sketches
          mkdir -p book_compilation
          mkdir -p book_to_publish  # Ensure cover output folder exists

      - name: Run download_from_dropbox.py
        id: download_dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python3 download_from_dropbox.py "/artland_ai/google_photo_albums" "google_photo_albums" "${{ secrets.REFRESH_TOKEN }}" "${{ secrets.APP_KEY }}" "${{ secrets.APP_SECRET }}" "download_log.txt"

      - name: Generate Python scripts from Secrets
        env:
          ARTISTIC_PAINTING_PROCESSOR: "${{ secrets.ARTISTIC_PAINTING_PROCESSOR }}"
          ADD_FADING_EDGES: "${{ secrets.ADD_FADING_EDGES }}"
        run: python3 generate_scripts.py

      - name: Run image processing loop
        run: |
          chmod +x process_images.sh
          ./process_images.sh

      - name: Generate background image
        run: python3 generate_background.py

      - name: Generate magazine cover
        run: python3 generate_cover.py  # NEW STEP: Generates PDF/JPG cover

      - name: Upload processed sketches and book compilation images to Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python3 upload_to_dropbox.py "${{ secrets.REFRESH_TOKEN }}" "${{ secrets.APP_KEY }}" "${{ secrets.APP_SECRET }}"



